### ISSUE TITLE
Bitbucket Webhook is sent but Jenkins log says: Matched 0.

### ISSUE THREAD

**Issue by raulney** [amuniz/bitbucket-branch-source-plugin#18]
Hello all,

I am facing an issue with Webhooks being triggered by Bitbucket plugin but Jenkins plugins is not matching the event to any jobs. I have a Bitbucket Team/Organization job configured and it is capable of detecting all the branches (master and PRs).

Already dumped the TCP packets using Wireshark and the POST requests for the events are being sent with the complete payload with all the information about the event inside.

Also tried to configure the job as a Multibranch Pipeline instead of a Bitbucket Team/Organization folder but had no luck either.

Jenkins plugin logs says:

[Tue Mar 27 14:54:23 UTC 2018] Received com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$1 CREATED event from Bitbucket_Server_IP ⇒ http://Jenkins_IP:8080/bitbucket-scmsource-hook/notify with timestamp Tue Mar 27 14:54:23 UTC 2018
[Tue Mar 27 14:54:23 UTC 2018] Finished processing com.cloudbees.jenkins.plugins.bitbucket.hooks.PullRequestHookProcessor$1 CREATED event from Bitbucket_Server_IP ⇒ http://Jenkins_IP8080/bitbucket-scmsource-hook/notify with timestamp Tue Mar 27 14:54:23 UTC 2018. Matched 0.

Jenkins ver. 2.107.1
Bitbucket Branch Source Plugin ver. 2.2.10
Post Webhooks for Bitbucket ver. 1.6.2

**Comment by fdvieira** [comment]
Did you solve this? I'm facing the same issue.
